<a href="https://colab.research.google.com/github/techcoderR/Numpy-Exercise/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---
#NumPY exercise


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


## Array Creation
#### Create a numpy array of size 10 filled with zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a numpy array with value ranging from 10 to 49

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a numpy matrix of 2*2 integers, filled with ones.

In [9]:
np.ones([2,2] ,dtype=np.int)

array([[1, 1],
       [1, 1]])

#### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [10]:
np.ones([3,2],dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

####Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [29]:
x=np.random.randint(100,size=[4,4],dtype=np.int)

np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [28]:
x=np.random.randint(100,size=[4,4],dtype=np.int)

np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

####Create a numpy matrix of 4*4 integers, filled with fives.

In [27]:
a=np.ones((4,4),dtype=np.int)
#a=a*5
print(a*5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [30]:
x=np.random.randint(100,size=[4,4],dtype=np.int)

(np.ones_like(x))*7


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [32]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  Create a numpy array, filled with 3 random integer values between 1 and 10.

In [38]:
x=np.random.randint(10,size=3)

In [39]:
x

array([6, 8, 2])

#### Create a 3x3x3 numpy matrix, filled with random float values.

In [40]:
np.random.randn(3,3,3)

array([[[ 0.54930752, -1.04861697, -0.43177511],
        [-0.01750912,  0.506657  ,  0.38408064],
        [-0.7738779 , -1.07348491, -0.47786063]],

       [[ 0.93784858,  1.21194784,  0.96863367],
        [-1.95773057,  1.11595044,  0.53878578],
        [ 0.9642446 ,  0.32161624, -0.81536095]],

       [[ 0.02037053,  1.3638636 ,  0.82297563],
        [ 0.62313149, -0.08413076,  1.15782731],
        [-0.40884808, -0.23552854, -2.42601789]]])

In [45]:
np.random.randint(100,size=[3,3,3]) ##only plot int value

array([[[71, 57, 87],
        [22, 87, 50],
        [27, 18, 83]],

       [[ 4, 17, 88],
        [10, 85, 88],
        [66, 29, 52]],

       [[ 8, 68, 52],
        [81, 99, 70],
        [80,  2, 30]]])

In [46]:
np.random.random(size=[3,3,3]) #alternate

array([[[0.19819056, 0.74532474, 0.00586091],
        [0.10547274, 0.54237804, 0.34787987],
        [0.49286494, 0.53388477, 0.45140862]],

       [[0.16209319, 0.49707477, 0.41751453],
        [0.83070764, 0.54855433, 0.00326533],
        [0.52395469, 0.81835861, 0.40110699]],

       [[0.46258038, 0.19308981, 0.94032966],
        [0.98461074, 0.69054211, 0.79996287],
        [0.14141954, 0.58890396, 0.4584146 ]]])

####Given the X python list convert it to an Y numpy array

In [49]:
x=[1,2,3,4]
print(x,type(x))
y=np.array(x)
print(x,type(y))

[1, 2, 3, 4] <class 'list'>
[1, 2, 3, 4] <class 'numpy.ndarray'>


####  Given the X numpy array, make a copy and store it on Y.

In [53]:
x=np.array([1,2],dtype=int)
y=np.copy(x) ##copy the array
print(x,id(x))
print(y,id(y))

[1 2] 140404367210576
[1 2] 140404366676656


#### Create a numpy array with numbers from 1 to 10

In [54]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a numpy array with the odd numbers between 1 to 10

In [55]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### Create a numpy array with numbers from 1 to 10, in descending order.

In [60]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [59]:
np.arange(1, 11)[::-1] #alternate

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [63]:
np.random.randint(8,size=[3,3]) #using random functiom

array([[5, 7, 2],
       [0, 4, 3],
       [6, 5, 6]])

In [64]:
np.arange(9).reshape(3,3) #using arange function

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Show the memory size of the given Z numpy matrix

In [73]:
z=np.zeros((3,3))
print(z.itemsize*(z.size))


72


## Array indexation

#### Given the X numpy array, show it's first element

In [84]:
a=np.array([1,2,3,4,5])
a[1]

2

####  Given the X numpy array, show it's first three elements


In [82]:
a[0:3]

array([1, 2, 3])

####  Given the X numpy array, show all middle elements

In [80]:
a[1:-1]

array([2, 3, 4])

####  Given the X numpy array, show the elements in reverse position

In [87]:
a[::-1]

array([5, 4, 3, 2, 1])

#### Given the X numpy array, show the elements in an odd position

In [88]:
a[::2]

array([1, 3, 5])

#### Given the X numpy matrix, show the first row elements

In [89]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

#### Given the X numpy matrix, show the last row elements

In [91]:
X[-1]

array([13, 14, 15, 16])

#### Given the X numpy matrix, show the first element on first row

In [93]:
X[0,0]

1

#### Given the X numpy matrix, show the last element on last row

In [95]:
X[-1,-1]

16

#### Given the X numpy matrix, show the middle row elements

In [97]:
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

#### Given the X numpy matrix, show the first two elements on the first two rows

In [99]:
X[0:2,0:2]

array([[1, 2],
       [5, 6]])

#### Given the X numpy matrix, show the last two elements on the last two rows

In [101]:
X[2:,2:]

array([[11, 12],
       [15, 16]])